### ISSUE TITLE
 Unable to infer an appropriate name for the query - query: `INSERT INTO analysis_email (email, analysis_id) VALUES ($1, $2)`

### ISSUE THREAD

**Issue by simplenotezy** [JasonShin/sqlx-ts#116]
I am getting the following error:

```
❯ npm run sql:generate

> template-worker-typescript@1.0.0 sql:generate
> npx sqlx-ts ./src --config ./.sqlxrc.json -g

[INFO] Scanning "./src" for SQLs with extension Ts
Error: [E001] Unable to infer an appropriate name for the query - query: `INSERT INTO analysis_email (email, analysis_id) VALUES ($1, $2)`

Location:
    src/ts_generator/generator.rs:51:76
```

From the following line:

```ts
    await this.db.query({
      text: sql`INSERT INTO analysis_email (email, analysis_id) VALUES ($1, $2)`,
      values: [this.email.from, id],
    });
```

By the way; it would also be helpful to know which line and file it found the query in

**Comment by simplenotezy** [comment]
Oups; that won't work. It generates invalid type files

export type InsertEmailAnalysis*/insertIntoEmailAnalysis(email,AnalysisId)Values($1,$2)Params = [string, any];

**Comment by simplenotezy** [comment]
OK, so the issue was I was needing to define a const that would do something with the result:

```
    cosnt myQueryName = await this.db.query({
      text: sql`/* @name: InsertEmailAnalysis */INSERT INTO email_analysis (email, analysis_id) VALUES ($1, $2)`,
      values: [this.email.from, id],
    });

**Comment by JasonShin** [comment]
@simplenotezy hello, this is actually an expected behaviour

```
await this.db.query({
      text: sql`INSERT INTO analysis_email (email, analysis_id) VALUES ($1, $2)`,
      values: [this.email.from, id],
});
```
If this code is provided to sqlx-ts, it cannot determine a name of the query to be used when generating the interface (`<name>Params`, `I<name>Result`, `I<name>Query`)

As a result, you need to provide either
- from TypeScript, you can declare a `const` variable, like what you suggested `const myQueryName`. sqlx-ts will pick up the variable name and use that when generating the query types
- if the statement is not required to be declared against a variable, you can give it an annotation
```
+const myQueryName = await this.db.query({
  text: sql`/* @name: InsertEmailAnalysis */INSERT INTO email_analysis (email, analysis_id) VALUES ($1, $2)`,
  values: [this.email.from, id],
});
```

Please checkout https://jasonshin.github.io/sqlx-ts/reference-guide/4.5.annotations.html for more information

**Comment by simplenotezy** [comment]
thanks Jason. It makes sense. I think it could be cool if

A) it would not break the script, maybe just output a warning
B) it would ignore the name generation process and simply validate the query if it can be run or not
