### ISSUE TITLE
camel case renaming does not work

### ISSUE THREAD

**Issue by joleeee** [JasonShin/sqlx-ts#99]
this undocumented feature doesnt work because when i ex. select `date_local`, it returns an object `{date_local: ...}`, which can be seen by `console.log`-ing it. However, the generated type by sqlx-ts types it as `{dateLocal: ...}`, which makes no sense.

I also cannot manage to disable this, i tried:
```
    "generateTypes": {
      "enabled": true,
      "generate_path": "src/routes/api/gen.ts",
      "convertToCamelCaseColumnName": false,
      "convert_to_camel_case_column_name": false
    },
```

**Comment by joleeee** [comment]
Ok turns out the config in the [guide](https://jasonshin.github.io/sqlx-ts/guides/2.configuration.html) doesnt work because it uses camel case for `generateTypes`, while it should be snake case.

![image](https://github.com/JasonShin/sqlx-ts/assets/24441708/1aaf5a5d-d735-4984-a4e3-183f67748db0)

This is the workaround I'm doing right now:
```ts
{
    "generate_types": {
      "enabled": true,
      "generate_path": "src/routes/api/gen.ts", // <-- doesnt work ???
      "convertToCamelCaseColumnName": false
    },
    "connections": {
      "default": {
        ...
      }
    }
  }
```
And then
```sh
$ npx sqlx-ts ./src/routes --config .sqlxrc.json --generate-path src/routes/api/gen.ts
```

**Comment by JasonShin** [comment]
Hello there, thanks for this. Will take a look shortly

**Comment by simplenotezy** [comment]
I can confirm this configuration works:

```json
{
  "generate_types": {
    "enabled": true,
    "convertToCamelCaseColumnName": true
  }
}
```

Changing `convertToCamelCaseColumnName` to true/false will change the generated types, however, the results (if the value is inspected) is _always_ `snake_case`. So setting `convertToCamelCaseColumnName` to true does not actually work.

**Comment by simplenotezy** [comment]
For now, my current workaround is to manually cast to camel case using this function:

```ts
import { camelCase, mapKeys, pickBy } from 'lodash';
export default <T = any>(input: any, prefix: string = ''): T =>
  mapKeys(
    pickBy(input, (_, k: string) => k.startsWith(prefix)),
    (_, key) => camelCase(key.replace(prefix, ''))
  ) as T;
```

**Comment by JasonShin** [comment]
Hi guys, I've been testing this and I can see the issue.
- convertToCamelCase is always true because I've set the default of this to true https://github.com/JasonShin/sqlx-ts/blob/main/src/common/config.rs#L117 here.
- The results are always camcelCase for wildcard queries because the formatter is not running against the wildcard query translation https://github.com/JasonShin/sqlx-ts/blob/main/src/ts_generator/sql_parser/expressions/translate_wildcard_expr.rs#L74

To resolve this issue, I will
- fix the issue with convertToCamelCase in general
- but also I'm leaning toward deprecating this, instead, I will prefer more generic configuration where people can choose camcelCase, snake_case, PascalCase and so on freely
- I can see the tests that I wrote are flawed because none of them are actually catching this issue properly

In the upcoming update
- convertToCamelCase will work, but it will be deprecated, no longer supported and will be dropped in v1.0.0
- introduce more general flag to encapsulate global casing config - also the config should work for all query types - select, insert, delete, update

**Comment by JasonShin** [comment]
This is fixed - I am going to work on introducing a flexible configuration to set casing
